wecode-bootcamp-korea/justcode-5-1st-codeisneverthat-front

src/styles/reset.scss
=> Add: adding setup

src/pages/Login/Login.js, src/pages/Login/Login.module.scss, src/pages/Signup/Signup.js, src/pages/Signup/Signup.module.scss
- [o] 레이아웃 구현
<br />
- 회원가입, 로그인 페이지 구현
<br />
1. 회원가입페이지
- animation css 추가
=> Add: Feature/signup login (회원가입/로그인 페이지 구현)

package-lock.json, package.json, public/index.html, src/components/Header/Header.js, src/components/Header/Header.module.scss, src/components/Header/modal/Search.js, src/components/Header/modal/Search.module.scss, src/modal/index.js, src/modal/modal.module.scss, src/pages/Home/Home.js, src/pages/Router.js
Fix: index.html 에 modal 추가, Router.js > Header, Footer 추가, Home > Header, Footer 삭제
- [o] 레이아웃 구현
<br />
- header > search bar 추가 구현
- Router.js 에 header, footer import 
<br />
1. portal modal 구현 
- modal > modal.js, modal.modules.scss 추가하여 portal modal 구현
- public > index.html 에 modal <div> 추가
2. Search Bar 구현 
- Header > Search 폴더 생성
- Search.js, Search.module.scss 추가
- props 로 showing 전달 하여 x 버튼 또는 배경 클릭시 모달팝업 닫힘 구현
<br />
- modal 을 처음 구현하는 것이기 때문에, 어떻게 연결하는지 새로 알게 되었습니다.
=> Add: Header > Search 추가

src/components/Header/modal/Search.module.scss, src/modal/index.js, src/modal/modal.module.scss, src/pages/Login/Login.js, src/pages/Signup/Signup.js
- [o] 버그 수정
<br />
- search box 의 input 클릭시 닫힘 현상 수정
<br />
1. modal 구조 변경
- modal > index.js 의 돔 구조 변경
=> Fix: Search modal 변경

src/components/Header/Header.js, src/components/Header/Header.module.scss, src/pages/Login/Login.js, src/pages/Router.js, src/pages/Signup/Signup.js
- [o] 기능 추가
<br />
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현
<br />
1. 회원가입 input 입력시 회원가입 성공
- 입력창에 변화가 일어날 때 마다 setInputs 저장
- 회원성공 message 반환
2. 로그인 input 입력시 로그인 성공
- 로그인 input 입력시 성공
- 로그인 성공 후 token을 localstorage 저장
=> Add: 회원가입, 로그인 추가

src/pages/Home/Home.js, src/pages/Home/Home.module.scss, src/pages/Router.js
<br />
Add: Main page 레이아웃 및 기능 구현
<br />
<br />
<br />
없음
=> Add: Main page 레이아웃 및 기능 구현

src/components/Header/Header.js
<br />
1. Header.js>collection 링크 변경
<br />
=> Fix: Header.js collection 링크 변경

src/components/CartItem/Items.jsx, src/components/Header/Header.js, src/pages/Cart/Cart.js, src/pages/Login/Login.js, src/pages/Router.js, src/store/UserStore.js
<br />
- context API 사용하여 Router.js 에서 전역 변수 넘기기,
- cart>items.jsx 수정중
<br />
1. context API 구현
- store 폴더 생성 후 createContext 사용하여 UserContext 생성
- token useState 세팅
- return 안에 넘길 value 값 넣고, {props.children}으로 props 넘김
3. items.jsx -> cart 연동 수정중 
<br />
- context API 를 사용하여 전역 변수(?) 를 생성하여 사용하는 법을 배웠습니다.
=> Add: context api (Fix: Header.js, Router.js, Login.js), Cart>Items.js

src/components/CartItem/Item.jsx, src/components/CartItem/Items.jsx, src/pages/Cart/Cart.js
<br />
- 카트의 데이터 read 수정 
<br />
1. 카트 데이터 연결
- `useEffect(() => {
setArticles(items);
}, [items]);` 를 사용하여 items가 있을때 items 값을 변경
2. itmes.jsx input 에러 수정
- value 값 + readonly 추가
=> Fix: itmes.jsx > item map 수정, cart.js> mock data 삭제

src/pages/Product/Product.js, src/styles/reset.scss
- [o] 기능 추가
<br />
- Backend Data Fetching
<br />
1. 백엔드 데이터 연동 후 적용
- 데이터를 가져온 뒤 조건부 랜더링 처리를 통해 데이터들을 알맞게 넣었습니다.
<br />
- data fetch, 조건부 랜더링, map()을 통해 데이터 뿌려주기를 준수하게 구현할 수 있게 되었습니다.
<br />
- 없습니다.
=> Fix: Backend Data Fetching Complete

src/components/Footer/Footer.module.scss, src/components/Header/Header.js, src/components/Header/Header.module.scss, src/components/Header/modal/Search.module.scss, src/components/SizeButton/SizeButton.js, src/components/SizeButton/SizeButton.module.scss, src/pages/Cart/Cart.module.scss, src/pages/Collections/Block.js, src/pages/Collections/Collections.js, src/pages/Collections/Collections.module.scss, src/pages/Login/Login.js, src/pages/Login/Login.module.scss, src/pages/Product/Product.js, src/pages/Product/Product.module.scss, src/pages/Signup/Signup.module.scss, src/pages/Top/Item.js, src/pages/Top/Item.module.scss, src/pages/Top/Top.js, src/styles/reset.scss
<br />
- 반응형 추가 구현
<br />
1. 반응형 구현
- min-width :1140px 로 반응형 추가 
- font-size:62.5%; 로 reset.scss 추가 후 브레이크포인트로 font-size 추가
=> 반응형 scss 추가, 코드 정리

src/components/Header/Header.js, src/components/Header/Header.module.scss, src/components/SizeButton/SizeButton.module.scss, src/pages/Collections/Block.js, src/pages/Collections/Block.module.scss, src/pages/Collections/Collections.js, src/pages/Collections/Collections.module.scss, src/pages/Home/Home.js, src/pages/Home/Home.module.scss, src/pages/Login/Login.module.scss, src/pages/Product/Product.js, src/pages/Signup/Signup.js, src/pages/Signup/Signup.module.scss, src/pages/Top/Top.js, src/styles/reset.scss
<br />
- 반응형 추가
<br />
1. @media query, rem 사용 으로 반응형 구현
=> 반응형 scss 추가

src/components/Product/modal/ImageDetail.js, src/components/Product/modal/ImageDetail.module.scss, src/components/Product/modal/Shipping.js, src/components/Product/modal/SizeFit.js, src/components/SizeButton/SizeButton.js, src/components/SizeButton/SizeButton.module.scss, src/modal/index.js, src/pages/Product/Product.js, src/pages/Product/Product.module.scss, src/styles/reset.scss
- [o] 레이아웃 구현
- [o] 기능 추가
- [o] 리팩토링
<br />
- 이미지 슬라이더 좌측의 썸네일 이미지 투명도 조절
- 세부 css 수정
<br />
1. 이미지 슬라이더 좌측의 썸네일 이미지 투명도 조절
- 메인 슬라이더에 나타나는 이미지에 맞게 좌측 썸네일에 선택되어 있지 않은 이미지는 투명도가 낮아짐
- 좌츨 썸네일 이미지 클릭시 메인 슬라이더의 사진이 바뀌며 투명도가 바뀜
2. 세부 css 수정
- Nesting 작업 & 세부 css 수정
<br />
- inline style로 조건부로 css를 바꾸는 것에 조금 더 익숙해졌다.
- Nesting 작업으로 유지보수성을 높였다.
- &:hover의 이해(&를 넣지않으면 그 안에 요소들에 각각 hover 효과가 적용되었는데 &:hover span을 통해 한꺼번에 hover효과가 나타나도록 수정하였고 그 원리와 개념을 이해하게 되었다.
<br />
- 추가로 modal 창을 구현하는데 modal이 처음 접하는 개념이라 개념을 이해하는데에 어려움을 느낌.
=> Add: Slider Opacity & Fix: Modify css, Fix typo

package-lock.json, package.json, src/components/CartItem/Item.js, src/components/CartItem/Items.js, src/components/CartItem/modal/CartModal.js, src/components/CartItem/modal/CartModal.module.scss, src/components/Header/Header.js, src/pages/Cart/Cart.js, src/pages/Cart/Cart.module.scss
<br />
- cart 모달 창 구현
<br />
1. src - components - Header -Header.js 수정
- CART 클릭시 기존 /cart로 링크로 되어있던 것 모달로 열리도록 수정
- useState 선언 (cartModal, setCartModal) 
- 단축평가로 cartModal 데이터 변경시 모달 실행되도록 구현
2. src - components - CartIem |  modal 폴더 생성
- CartModal.js, CartModal.module.scss 파일 생성
- 모달 구현 및 스타일 
3.  CSS nesting
src - components - CartIem -  modal | CartModal.module.scss
src - pages - Cart - Cart.module.scss
- nesting 적용
<br />
- css의 z index기능을 통해 모달 구현시 태그가 겹칠 때 우선순위를 정할 수 있게 됨
=> Add: Cart modal

src/components/CartItem/modal/CartModal.module.scss, src/components/Header/Header.js, src/pages/Signup/Signup.js
<br />
- 카트모달 animation 추가
- nav 카트 수량 표시 기능 작업중
<br />
1. 카트모달 animation 추가
- CartModal.module.scss 의 animation 추가
2. nav 카트 수량 표시 기능 작업중
- header의 fetch후 header 표시 
- 실시간 반영 안됨 -> (작업중)
<br />
- context API 를 써야할까..?
=> Fix: CartModal.module.scss animation 추가 & Add: cart nav 표시 추가중

src/components/CartItem/modal/CartModal.module.scss, src/components/Header/Header.js, src/store/UserStore.js
<br />
- cart와 search 클릭 후 스크롤시 사라지는 기능 구현
<br />
1. 스크롤 기능 추가 (Header.js)
- throttle, useMemo 추가 
- ```const throttledScroll = useMemo(
() =>
throttle(() => {
const nextTabnavOn = window.scrollY > window.scrollY + 100;
if (nextTabnavOn !== cartModal) setCartModal(nextTabnavOn);
if (nextTabnavOn !== isShowing) setIsShowing(nextTabnavOn);
}, 300),
[cartModal, isShowing]
);
useEffect(() => {
window.addEventListener('scroll', throttledScroll);
return () => {
window.removeEventListener('scroll', throttledScroll); //clean up
};
}, [throttledScroll]);`
<br />
- throttle와 useMemo 를 사용하여 최적화 하는 방법을 알게되었다.
=> Add: cart&search scroll 시 사라지는 기능 추가

src/components/SizeButton/SizeButton.js, src/pages/Product/Product.js
<br />
- 오타 수정
<br />
1.  product_detatail_id -> product_details_id 로 변경
=> Fix: product.js&SizeButton.js > product_detatail_id -> product_details_id 로 변경

.env
=> Fix: .env BASE_URL 수정

src/components/CartItem/Item.js, src/components/CartItem/modal/CartModal.js, src/components/Header/Header.js, src/pages/Cart/Cart.js, src/pages/Login/Login.js, src/pages/Product/Product.js, src/pages/Signup/Signup.js, src/pages/Top/Top.js
=> Fix: import BASE_URL 경로

.env
=> Fix: .env 파일 수정

.gitignore
<br />
Fix: .gitignore에서 .env 추가
=> Fix: .gitignore에서 .env 추가

.env
=> Fix: .env 파일 제거

src/components/Product/modal/ImageDetail.js, src/components/Product/modal/ImageDetail.module.scss, src/pages/Product/Product.js, src/pages/Product/Product.module.scss, src/pages/Product/modal/ImageDetail.js, src/pages/Product/modal/ImageDetail.module.scss, src/pages/Product/modal/Shipping.js, src/pages/Product/modal/SizeFit.js
<br />
- Image Detail modal창 구현
<br />
1. Image Detail Modal 창 추가
- 모달 레이아웃 구현
- 모달 scss 적용
- 모달창 이미지 삽입
<br />
- 모달창을 구현할 수 있게 되었다.
- 모달 Props를 이해했다.
<br />
- 없음
=> Add: Image Detail Modal & Fix: Context, Delete useless useState

src/pages/Collections/Block.js, src/pages/Product/Product.js, src/pages/Product/modal/ImageDetail.module.scss, src/pages/Product/modal/Shipping.js, src/pages/Product/modal/Shipping.module.scss, src/pages/Product/modal/SizeFit.js, src/pages/Product/modal/SizeFit.module.scss
<br />
- Size & Fit Modal
- Shipping Modal
- Add Query Params page and Link to page
<br />
1. Size & Fit Modal, Shipping Modal
- 모달창 구현
- CLOSE 버튼 클릭 또는 모달창 바깥 부분 클릭시 모달창 꺼짐
- 레이아웃 구성
- 화면상 모달 위치 지정
2. Add Query Params page and Link to page
- Query Prams가 세부적으로 나눠지고 그에 따라 Fetch한 데이터 다시 필터링하여 조건에 맞게 데이터를 뿌려줌
- 링크로 연결 시켜주어야 하는데 url 재설정이 필요해보임.
<br />
- 모달창에 대한 이해도가 높아졌다.
- 레이아웃, position, props를 이용한 모달 구현에 친해졌다.
- URLSearchParams 객체를 이용하여 url에 접근할 수 있게 되었다.
- 객체 내의 여러 함수들을 통해서 url에 좀 더 효율적으로 접근하는 방법을 알게 되었다.
<br />
- product.js의 url 틀을 수정하여 <Link> 태그 내의 to=" "를 넣어주는 작업이 추후에 필요함
=> Add: Size&Fit Modal, Query Prams page(Not End)

src/pages/Product/Product.js
<br />
- Product 페이지에서 다른 칼라를 선택시 페이지 이동
<br />
1. Product 페이지에서 다른 칼라 선택하면 상품이 다른 색으로 변경
- url을 분리해서 product_id를 location.search에서 변수로 선언해서 쓰고 product_color_id를 map 돌려서 이미지의 product_color_id를 따서 Link로 연결
<br />
- useLocation()과 URLSearchParams객체를 통해서 url을 분리해서 원하는 값을 바꾸고 필요한 값을 넣을 수 있게 되었다
<br />
- 없음
=> Add: Link to Query Prams page

src/config.js, src/pages/Collections/Block.js, src/pages/Collections/Block.module.scss, src/pages/Collections/Collections.js, src/pages/Collections/Collections.module.scss, src/pages/Top/Item.js, src/pages/Top/Item.module.scss, src/pages/Top/Top.js
<br />
- top collection updated 
<br />
추가 구현 사항 이외의 update
<br />
<br />
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> top collection updated

src/pages/Cart/Item.js
<br />
- 아이디, 비밀번호 입력창을 사용한 로그인 기능 구현 (예시)
<br />
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력
2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현
<br />
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)
<br />
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)
=> Fix: Cart페이지에서 fetch 받아오는 부분에 item id 추가
